# See options at https://github.com/coogie/oscailte
# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://blog.openenergymonitor.org
title: Blog | OpenEnergyMonitor
subtitle: OpenEnergyMonitor Blog
author: Glyn Hudson
simple_search: https://encrypted.google.com/search
description: OpenEnergyMonitor Blog

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
#subscribe_rss: /atom.xml
#subscribe_email: support@openenergymonitor.zendesk.com
# RSS feeds can list your email address if you like
email: support@openenergymonitor.zendesk.com

# ----------------------- #
#    OEM CUSTOM           #
# ----------------------- #
ex_image_path: https://openenergymonitor.org/files/blog_images
image_path: /images

#![image-description]({{site.image_path}}/photo.jpg)


# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

permalink: /:year/:month/:title/
source: source
destination: public/
plugins_dir: plugins
code_dir: downloads/code
category_dir: categories
markdown: kramdown
timezone: UTC

syntax_highlighter_opts:
  input: GFM
  auto_ids:       false
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  parse_block_html: true
  coderay: true

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      nil
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               class

highlighter: rouge

gems:
  - jekyll-time-to-read
#  - octopress-filters
  - octopress-include-tag
#  - jekyll-feed

paginate: 10          # Posts per page on the blog index
paginate_path: "posts/:num"  # Directory base for pagination URLs eg. /posts/2/
recent_posts: 10       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles
excerpt_separator: "<!--more-->"

titlecase: true       # Converts page and post titles to titlecase

# Each layout uses the default asides, but they can have their own asides instead. Simply uncomment the lines below
# and add an array with the asides you want to use.
# blog_index_asides:
# post_asides:
# page_asides:

collections:
  advanced:
    output: true

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user: openenergymonitor
github_repo_count: 5
github_show_profile_link: true
github_skip_forks: true

# Twitter
twitter_user: openenergymon
twitter_tweet_button: true

# Google +1
google_plus_one: true
google_plus_one_size: standard

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user: +openenergymonitor
googleplus_hidden: true

# Pinboard
pinboard_user:
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3

# Disqus Comments
disqus_short_name: openenergymonitor
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-10321170-4

# Facebook Like
facebook_like: true

social:
  twitter:
    account: openenergymon
