---
layout: post
title: A battery powered wireless energy monitor sensor node.
date: '2011-01-01T16:49:00.000-08:00'
author: Trystan Lea
categories: 
modified_time: '2011-01-01T16:55:07.853-08:00'
blogger_id: tag:blogger.com,1999:blog-2472065242652647619.post-5241258934333403278
blogger_orig_url: http://openenergymonitor.blogspot.com/2011/01/battery-powered-wireless-energy-monitor.html
---

<a onblur="try {parent.deselectBloggerImageGracefully();} catch(e) {}" href="http://openenergymonitor.org/emon/sites/default/files/ctpulseboost.png"><img style="display:block; margin:0px auto 10px; text-align:center;cursor:pointer; cursor:hand;width: 400px;" src="http://openenergymonitor.org/emon/sites/default/files/ctpulseboost.png" border="0" alt="" /></a><br /><span class="Apple-style-span"  style="font-size:medium;">A battery powered wireless energy monitor sensor node in development:</span><div><span class="Apple-style-span"><b><span class="Apple-style-span"  style="font-size:medium;"><br /></span></b></span></div><div><span class="Apple-style-span"><b><span class="Apple-style-span"  style="font-size:medium;">Main features</span></b></span></div><div><ul><li><span class="Apple-style-span"><span class="Apple-style-span"  style="font-size:medium;">1 CT input</span></span></li><li><span class="Apple-style-span"><span class="Apple-style-span"  style="font-size:medium;">2 </span><span class="Apple-style-span"><span class="Apple-style-span"  style="font-size:medium;">Pulse inputs</span></span></span></li><li><span class="Apple-style-span"><span class="Apple-style-span"><span class="Apple-style-span"  style="font-size:medium;">Boost converter for efficient battery use</span></span></span></li><li><span class="Apple-style-span"><span class="Apple-style-span"><span class="Apple-style-span"  style="font-size:medium;">RF board connect</span></span></span></li></ul><span class="Apple-style-span"  style="font-size:medium;"><a href="http://openenergymonitor.org/emon/node/115">http://openenergymonitor.org/emon/node/115</a></span></div><div><span class="Apple-style-span"><span class="Apple-style-span"  style="font-size:medium;"><br /></span></span></div><div><span class="Apple-style-span"  style=" ;font-size:15.8333px;"><br /></span></div>