---
layout: post
title: Measuring heat flux in and out of a hot water cylinder
date: '2012-05-24T12:07:00.001-07:00'
author: Trystan Lea
categories:
- SHW
modified_time: '2012-05-25T03:12:38.622-07:00'
blogger_id: tag:blogger.com,1999:blog-2472065242652647619.post-7136850294654335926
blogger_orig_url: http://openenergymonitor.blogspot.com/2012/05/measuring-heat-flux-in-and-out-of-hot.html
---

The heat input into a solar hot water cylinder is usually measured using a flow meter and two temperature sensors. Flow meters are quite expensive and require plumbing work to install. At OpenEnergyMonitor we're all for non-invasive monitoring methods! So..<br /><br />Can the heat flux in and out of a hot water cylinder (a fixed volume of water) be approximately calculated by measuring the average temperature change in the cylinder in kelvin per second and then multiplying by the volume of the cylinder and the specific heat of water?<br /><br />This method may only require two temperature sensors so will be considerably easier and more affordable than installing a flow meter.<br /><br />I've used an emonTx with two DS18B20 temperature sensors one positioned in the temperature sensor sleeve that is in the bottom half of the cylinder and the other positioned in the temperature sensor sleeve in the top half of the cylinder. The emontx is also monitoring the solar hot water collector temperature, controlling the solar hot water system and monitoring house electric consumption and solar pv electricity generation :) <br /><br /><b>Calculating heat flux</b><br /><pre>Heat Flux (Watts J/s) = Specific heat of Water (4186 J/kg/K) x Volume of cylinder (Litres)&nbsp;</pre><pre>x temperature change per second (K/s)</pre><pre></pre><b>The result</b><br />The heat flux is the blue plot and average cylinder temperature is the red plot. I have selected a period of time where the electric immersion heater is on. Feel free to explore the data by using the zoom and pan buttons.  <iframe frameborder="0" height="400px" marginheight="0" marginwidth="0" scrolling="no" src=" http://vis.openenergymonitor.org/emoncms3/Vis/test/power.php?apikey=622568853818f6a340569ec059e340f8&amp;feedA=22&amp;feedB=23" width="700px"></iframe>  <br /><br />I'm surprised by how good the initial results seem to be. I know that the electric immersion heater consumes about 3400W from my electricity monitoring and the heat flow input calculated via the above method gives pretty much the same power input plus or minus a few hundred watts or so.<br /><br /><b>Questions for further development</b><br />What is the minimum number of temperature sensors needed and what are their optimum positions to give best results? What is the effect of stratification?<br /><br /><b>Download the source code:&nbsp;</b><b><a href="http://openenergymonitor.org/emon/sites/default/files/hotwatercylinder.zip">hotwatercylinder.zip</a></b><br /><br />