---
layout: post
title: Triac based MK2 PV Controller by Calypso Rye
date: '2012-07-16T06:42:00.000-07:00'
author: Trystan Lea
categories:
- electronics
- solarPV
modified_time: '2012-07-17T02:19:49.194-07:00'
thumbnail: http://3.bp.blogspot.com/-Y8lRjQvqoZg/UAQXPSAleMI/AAAAAAAACdU/9CxAGNIB73Y/s72-c/IMGP9704.JPG
blogger_id: tag:blogger.com,1999:blog-2472065242652647619.post-4868201712351213015
blogger_orig_url: http://openenergymonitor.blogspot.com/2012/07/triac-based-mk2-pv-controller-by.html
---

<div class="separator" style="clear: both; text-align: center;"></div><div class="separator" style="clear: both; text-align: center;"><a href="http://3.bp.blogspot.com/-Y8lRjQvqoZg/UAQXPSAleMI/AAAAAAAACdU/9CxAGNIB73Y/s1600/IMGP9704.JPG" imageanchor="1" style="margin-left: 1em; margin-right: 1em;"><img border="0" height="300" src="http://3.bp.blogspot.com/-Y8lRjQvqoZg/UAQXPSAleMI/AAAAAAAACdU/9CxAGNIB73Y/s400/IMGP9704.JPG" width="400" /></a></div><br /><br /><a href="http://openenergymonitor.org/emon/user/956">Calypso Rye</a> writes:<br /><br /><div style="background-color: #dddddd; font-size: 90%; padding: 10px;">Based on the standard VI sketch which uses calcVI() in EmonLib, I’ve had a system in place for the last couple of months which diverts surplus PV power to our immersion heater.  This system has proved to be both effective and reliable, and I am most grateful for everyone who has helped me along the way.  The main downside to this arrangement is that it requires an expensive item of third-party kit to distribute the power.  (I know that others have found cheaper ways, but my Carlo Gavazzi unit cost me £70).<br /><br />Other contributors to this forum have shown that a standard triac can be easily controlled by an Arduino.  By using a zero-crossing detector such as the Motorola MOC3041, it should be possible for the Arduino to allocate mains cycles directly to the load rather than delegating this task to a separate device.<br /><br />A Mk2 system of this type has been working in our garage for the last few days.  The sketch and a schematic diagram are attached, its main features being:<br /><br />- a comprehensive 'debug' mode which allows real world conditions to be simulated ;<br /><div><br />- a continuous mode of operation, for both measurement and distribution of power;</div><div><br />- an "energy bucket" concept which gives precise control of surplus power;<br /><br />- interleaved windows for measurement and generation, each only 20mS;<br /><br />- a rapid response time to changing conditions (50mS);<br /><br />- suitable timing for 'arming' a zero-crossing trigger device;<br /><br />- a single LPF which determines the dc-offset of raw VI samples;<br /><br />- a programmable safety margin for biassing import v. export;<br /><br />- minimal calibration is required.</div></div><br />Read the full post on the forum here: <a href="http://openenergymonitor.org/emon/node/841">http://openenergymonitor.org/emon/node/841</a>