---
layout: post
title: Emoncms multilingual support
date: '2012-05-19T12:14:00.001-07:00'
author: Trystan Lea
categories:
- emoncms
modified_time: '2012-05-25T03:10:04.172-07:00'
thumbnail: http://3.bp.blogspot.com/-5cUcK4Ib6Cs/T7fwkPI422I/AAAAAAAACb4/eHnrSwCbGKQ/s72-c/lang_copy.png
blogger_id: tag:blogger.com,1999:blog-2472065242652647619.post-8879749349318709570
blogger_orig_url: http://openenergymonitor.blogspot.com/2012/05/emoncms-multilingual-support.html
---

The latest update to emoncms adds a basic implementation of multilingual support.<br /><a href="https://github.com/openenergymonitor/emoncms3">https://github.com/openenergymonitor/emoncms3</a><br /><br /><b>Adding a language</b><br /><br /><b>1) Make a copy of the folder Views/en and call it the language your creating a translation for, i.e cy for welsh:</b><br /><b><br /></b><br /><div class="separator" style="clear: both; text-align: center;"><a href="http://3.bp.blogspot.com/-5cUcK4Ib6Cs/T7fwkPI422I/AAAAAAAACb4/eHnrSwCbGKQ/s1600/lang_copy.png" imageanchor="1" style="margin-left: 1em; margin-right: 1em;"><img border="0" height="100" src="http://3.bp.blogspot.com/-5cUcK4Ib6Cs/T7fwkPI422I/AAAAAAAACb4/eHnrSwCbGKQ/s320/lang_copy.png" width="320" /></a></div><b><br /></b><br /><br />.. or use a language that has already been translated from the emoncms_languages repo, i.e cy...<br /><a href="https://github.com/openenergymonitor/emoncms_languages">https://github.com/openenergymonitor/emoncms_languages</a>&nbsp;(feel free to send a pull request with your translations)<br /><br /><b>2) If your creating a new translation, translate each view script inside your language folder.</b><br /><br /><b>3) Add your language to the language options in index.php:</b><br /><br />Change the line:<br /><pre>$lang = &nbsp;$_GET['lang']; if ($lang=='en') $_SESSION['lang'] = $lang; else $lang = null;</pre><br />to (with your chosen language code)<br /><pre>$lang = &nbsp;$_GET['lang']; if ($lang=='en' || $lang=='cy') $_SESSION['lang'] = $lang; else $lang = null;</pre><br /><b>2) Add your language to the user_view language selector.</b><br />Until a better implementation is created, this needs to be done for each language.<br />In Views/en/user_view.php<br /><br />add (or your chosen language)<br /><br /><pre>&lt;option value="cy"&gt;Welsh&lt;/option&gt;</pre><br />below: <br /><pre>&lt;option selected value="en"&gt;English&lt;/option&gt;</pre><br /><br />Repeat this for the user_view that belongs to the language your adding and set the selected attribute to the added language.<br /><br />Any thoughts on a better way of implementing this is as always welcome.