---
layout: post
title: Reading Watt-hour data from an Elster A100C electricity meter using IrDA by
  Dave Berkeley
date: '2012-07-28T04:02:00.000-07:00'
author: Trystan Lea
categories:
- emonTx
- utility meters
modified_time: '2012-08-02T16:49:27.861-07:00'
blogger_id: tag:blogger.com,1999:blog-2472065242652647619.post-7949114499403398451
blogger_orig_url: http://openenergymonitor.blogspot.com/2012/07/reading-watt-hour-data-from-elster.html
---

<div><div class="separator" style="clear: both; text-align: center;"><a href="http://www.rotwang.co.uk/projects/images/DSCN3869.JPG" imageanchor="1" style="margin-left: 1em; margin-right: 1em;"><img border="0" height="272" src="http://www.rotwang.co.uk/projects/images/DSCN3869.JPG" width="400" /></a></div><br />If you have an Elster meter this is a fantastic way to read the exact accumulated watt hours that you have generated or used and can compliment and cross check a CT based measurement.<br /><br /><a href="http://www.rotwang.co.uk/">Dave Berkeley</a> writes:<br /><br /><div style="background-color: #dddddd; font-size: 90%; padding: 10px;">The A100C has an LCD display showing the number of kilowatt hours generated, but it also has two optical outputs. One flashes momentarily each time one watt hour is recorded. The second output is an infrared port which transmits the details of the meter, including accumulated Watt Hours, every second or so.<br /><br />There are lots of commercial power meter readers around, and many homemade ones too. But they all seem to simply count the 1Wh optical pulses. This does give you an accurate measure of instantaneous power usage / generation, but does not give accumulated totals. If you get a malfunction in the reader you will lose counts. If you count the IrDA output it always gives you accurate accumulated totals.</div><br />Read the full build guide here: <a href="http://www.rotwang.co.uk/projects/meter.html">Electricity Meter Reader</a><br /><br />and download the Arduino source code here: <a href="http://www.rotwang.co.uk/projects/docs/elec_meter.ino">elec_meter.ino</a><br /><br />The only thing you need to get this running on an arduino or an emontx is a&nbsp;<a href="http://www.alldatasheet.com/datasheet-pdf/pdf/92399/ETC/TSL261.html">TSL261R</a> optical sensor, the TSL261R has the same pin out as the  <a href="http://openenergymonitor.org/emon/sites/default/files/TSL257.pdf">TSL257</a>&nbsp;so can be connected to the emontx pulse input.<br /><br />We've put together a small kit <a href="http://shop.openenergymonitor.com/tsl261r-ir-sensor-kit/">available in the shop</a> of all the components needed to connect it to an emontx including the TSL261R a male 3.5mm jack, 1m of cable and&nbsp;heat-shrink to save needing to get all the components from different places.</div>