---
layout: post
title: Embodied Energy of Electronic Enclosure Materials
date: '2012-05-09T15:57:00.001-07:00'
author: Glyn Hudson
categories:
- sustainability
modified_time: '2012-05-13T06:21:47.018-07:00'
blogger_id: tag:blogger.com,1999:blog-2472065242652647619.post-7046278912624729978
blogger_orig_url: http://openenergymonitor.blogspot.com/2012/05/embodied-energy-of-electronic-enclosure.html
---

For us the&nbsp;underlying&nbsp;aim of energy monitoring is energy reduction. It's therefore important that over its useful life an energy monitoring system contributes to the saving of more energy than it involved in the embodied energy of it's production.<br /><br />Recently we have been having the discussion as to which material is&nbsp;environmentally&nbsp;better to use for electronic enclosures.<br /><br />So I did some research:<br /><br />Caution: The figures below were obtained from&nbsp;reputable&nbsp;sources but should not be taken on face value.<br /><ul><li>&nbsp;Extruded Aluminium takes approximately 40-80% <i>more </i>energy (KWh/Kg) to produce than ABS plastic [1][2] *</li></ul><ul><li>Aluminium is widely and easily recycled (even if its been anodised&nbsp;[2]) and the recycled product is of just as high a quality as the&nbsp;original.&nbsp;ABS plastic can be recycled in some locations but the recycled product is of much lower quality than the&nbsp;original, 'downcycling' would be a better term!&nbsp;</li></ul><ul><li>Recycled aluminium takes about 30% <i>less </i>energy (KWh/Kg) &nbsp;to produce than ABS plastic [3].</li></ul><ul><li>Plastic is made from oil which is a non-renewable fossil fuel.</li></ul><ul><li>Aluminium is the most abundant metal in the Earth's crust, extracting it requires lots of electricity which could be generated from renewable sources.&nbsp;</li></ul>With current processing and recycling&nbsp;methods&nbsp;we think aluminium could be the best material to use, it does take more energy to produce in the first place but once produced it can be recycled again and again to make new things with little extra energy.<br /><br />What do you think?<br /><br />References:<br />[1]&nbsp;<a href="http://www.inference.phy.cam.ac.uk/withouthotair/c15/page_88.shtml">http://www.inference.phy.cam.ac.uk/withouthotair/c15/page_88.shtml</a><br />[2]&nbsp;<a href="http://www.victoria.ac.nz/cbpr/documents/pdfs/ee-coefficients.pdf">www.victoria.ac.nz/cbpr/documents/pdfs/ee-coefficients.pdf</a><br /><div><div>[3] <a href="http://www.worldchanging.com/archives/005656.html">http://www.worldchanging.com/archives/005656.html</a><br /><br />*Aluminium is about 2.6 times denser than plastic therefore a similar case made from plastic could be&nbsp;lighter. Further research is required before drawing a conclusion.&nbsp;</div></div>