---
layout: post
title: 'emonTx V3 AC Adapter Socket Error '
date: '2013-12-03T10:24:00.001-08:00'
author: Glyn Hudson
categories:
- emonTx
modified_time: '2013-12-05T06:39:32.508-08:00'
thumbnail: http://2.bp.blogspot.com/-ezZLN8e4mmM/Up4gJw0thlI/AAAAAAAArYU/PyYWKqSbZRY/s72-c/20131203_120842_Ffordd+Y+Parc.jpg
blogger_id: tag:blogger.com,1999:blog-2472065242652647619.post-5371392624446891507
blogger_orig_url: http://openenergymonitor.blogspot.com/2013/12/emontx-v3-ac-adapter-socket-error.html
---

<div class="separator" style="clear: both; text-align: left;">Just quick post to highlight a small bug in the first batch of emonTx V3...there had to be something!</div><div class="separator" style="clear: both; text-align: left;"><br /></div><div class="separator" style="clear: both; text-align: left;">The barrel-jack socket on the first batch of emonTx V3's has got a middle pin with a diameter of 2.5mm. Our adapters don't fit since they are 2.1mm..Doh!&nbsp;</div><div class="separator" style="clear: both; text-align: left;"><br /></div><div class="separator" style="clear: both; text-align: left;">To solve this we're shipping a little adapter unit with each emonTx V3:</div><div class="separator" style="clear: both; text-align: left;"><br /></div><div class="separator" style="clear: both; text-align: center;"><a href="http://2.bp.blogspot.com/-ezZLN8e4mmM/Up4gJw0thlI/AAAAAAAArYU/PyYWKqSbZRY/s1600/20131203_120842_Ffordd+Y+Parc.jpg" imageanchor="1" style="margin-left: 1em; margin-right: 1em;"><img border="0" height="240" src="http://2.bp.blogspot.com/-ezZLN8e4mmM/Up4gJw0thlI/AAAAAAAArYU/PyYWKqSbZRY/s320/20131203_120842_Ffordd+Y+Parc.jpg" width="320" /></a></div><br /><div class="separator" style="clear: both; text-align: center;"><a href="http://4.bp.blogspot.com/-SSQJPiSJWxs/Up4gJxZsQqI/AAAAAAAArYU/FTXyzm6gQto/s1600/20131203_120830_Ffordd+Y+Parc.jpg" imageanchor="1" style="margin-left: 1em; margin-right: 1em;"><img border="0" height="240" src="http://4.bp.blogspot.com/-SSQJPiSJWxs/Up4gJxZsQqI/AAAAAAAArYU/FTXyzm6gQto/s320/20131203_120830_Ffordd+Y+Parc.jpg" width="320" /></a></div><br />The AC-AC adapter is important and very useful on the emonTx V3 since it can power the unit as well as simultaneously providing an AC voltage sample for IRMS and Real Power readings.<br /><br />It's been a busy day of order fulfilment today, all emonTx V3, emonTH and emonTx Shield SMT pre-orders will be shipped by tomorrow. Sorry for the slight delay, waiting for these adapter units to arrive was the cause for the delay. Hopefully the orders should all arrive at the destinations before Christmas.<br /><br />Onwards! We're working hard to keep shipping out right up until Christmas. See my <a href="http://openenergymonitor.blogspot.com/2013/11/2013-christmas-ordering-info-royal-mail.html">last post regarding last postage days</a> for guaranteed delivery before Christmas.