---
layout: post
title: Kettle vs Blanket
date: '2014-12-08T03:55:00.002-08:00'
author: Glyn Hudson
categories:
- sustainability
modified_time: '2014-12-08T04:08:10.491-08:00'
thumbnail: http://2.bp.blogspot.com/-PRWQK4f8cpM/VIFxhBOblbI/AAAAAAABAjg/B0fmE75iFEs/s72-c/blanket.png
blogger_id: tag:blogger.com,1999:blog-2472065242652647619.post-7322033434011839158
blogger_orig_url: http://openenergymonitor.blogspot.com/2014/12/kettle-vs-blanket.html
---

One of the things I love about monitoring energy is that it can be used to answer questions and inform decisions.<br /><div><br /></div><div>In my household we have recently purchased an electric blanket, I had always associated such items as an indulgent luxury! However at this time of year the temperature in our bedroom is often only just about in double figures (old property with poor heating and frugal use) necessitating a seemingly moderate luxury of a hot water bottle to warm the bed up a little. &nbsp;&nbsp;</div><div><br /></div><div>I assumed using the new electric blanket would result in an increase in our power consumption, however the energy monitor proved me wrong!&nbsp;</div><div><br /></div><div>Having the electric blanket on for 30min used about 0.1KWh while boiling 1L of hot water to fill at hot water bottle used about 0.16KWh of energy, 60% more! Also the electric blanket does a much better job of warming the bed then the hot water bottle, after 30min it was almost uncomfortably hot even with an ambient temperature in the room of 11 degrees!&nbsp;</div><div><br /></div><div><table align="center" cellpadding="0" cellspacing="0" class="tr-caption-container" style="margin-left: auto; margin-right: auto; text-align: center;"><tbody><tr><td style="text-align: center;"><br /><a href="http://2.bp.blogspot.com/-PRWQK4f8cpM/VIFxhBOblbI/AAAAAAABAjg/B0fmE75iFEs/s1600/blanket.png" imageanchor="1" style="margin-left: auto; margin-right: auto;"><img border="0" src="http://2.bp.blogspot.com/-PRWQK4f8cpM/VIFxhBOblbI/AAAAAAABAjg/B0fmE75iFEs/s1600/blanket.png" height="456" width="640" /></a></td></tr><tr><td class="tr-caption" style="text-align: center;">200W Electric Blanket on for about 30 min</td></tr></tbody></table><div class="separator" style="clear: both; text-align: center;"></div><br /><table align="center" cellpadding="0" cellspacing="0" class="tr-caption-container" style="margin-left: auto; margin-right: auto; text-align: center;"><tbody><tr><td style="text-align: center;"><a href="http://1.bp.blogspot.com/-9WhNqhDkTyk/VIWOeVUmd6I/AAAAAAABAro/XBAaAxspyKg/s1600/Screenshot%2B2014-12-08%2Bat%2B11.38.19.png" imageanchor="1" style="margin-left: auto; margin-right: auto;"><img border="0" src="http://1.bp.blogspot.com/-9WhNqhDkTyk/VIWOeVUmd6I/AAAAAAABAro/XBAaAxspyKg/s1600/Screenshot%2B2014-12-08%2Bat%2B11.38.19.png" height="286" width="640" /></a></td></tr><tr><td class="tr-caption" style="text-align: center;">Kettle heating 1L of water to boiling</td></tr></tbody></table><br /></div>